theme: jekyll-theme-slate
title: Chassis Suspension Feature Importance of Self-Propelled Sprayers
description: Bailey Adams
Graduate Research Student
Department of Agricultural & Biosystems Engineering
Iowa State University
